# Generated by Django 3.2.8 on 2023-03-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Publigest', '0002_datascrapy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataScrapy',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=850, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('loves', models.IntegerField(blank=True, null=True)),
                ('hahas', models.IntegerField(blank=True, null=True)),
                ('wows', models.IntegerField(blank=True, null=True)),
                ('sads', models.IntegerField(blank=True, null=True)),
                ('hates', models.IntegerField(blank=True, null=True)),
                ('cares', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
    ]
