# Generated by Django 3.2.8 on 2023-03-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publigest', '0003_datascrapy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadesNombradas',
            fields=[
                ('ent_id', models.AutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(blank=True, max_length=850, null=True)),
                ('etiqueta', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
