# Generated by Django 3.2.8 on 2023-03-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publigest', '0004_entidadesnombradas'),
    ]

    operations = [

    ]
