# Generated by Django 3.2.8 on 2023-03-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publigest', '0005_palabrasclaves'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabrasClaves',
            fields=[
                ('kw_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyswords', models.CharField(blank=True, max_length=850, null=True)),
                ('text', models.CharField(blank=True, max_length=850, null=True)),
            ],
        ),
    ]
